# yaml-language-server: $schema=https://raw.githubusercontent.com/argoproj/argo-cd/master/manifests/crds/application-crd.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-components
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'git@github.com:sjgmdcx/my-gitops-app.git'
    targetRevision: HEAD
    path: clusters/talos-cluster  # Points to your Talos cluster configs / manifests
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tekton-shipwright-pipelines
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'git@github.com:sjgmdcx/my-gitops-app.git'
    targetRevision: HEAD
    path: tekton  # Or split into individual paths if you prefer
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: tekton-pipelines
  syncPolicy:
    automated:
      prune: true
      selfHeal: true